#Expyriment 0.9.0 (Python 3.7.3), .xpe-file, coding: cp1252
#date: Tue May 07 2019 10:01:03
#sha1: None
#modules: 
#display: size=(1280, 1024), window_mode=False, open_gl=2
#os: uname_result(system='Windows', node='IS151628', release='7', version='6.1.7601', machine='AMD64', processor='Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
4374,stderr,received,'Traceback (most recent call last):'
4374,stderr,received,'  File "scripts\\mttexp.py", line 335, in <module>'
4375,stderr,received,'    block_now.add_block(trial1991)'
4375,stderr,received,"AttributeError: 'Block' object has no attribute 'add_block'"
